# Generated by Django 6.0.5 on 2026-05-12 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва курсу')),
                ('description', models.TextField(verbose_name='Опис курсу')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва лекції')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Відеофайл')),
                ('subtitle_file', models.FileField(upload_to='subtitles/', verbose_name='Файл субтитрів (.vtt)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
        ),
    ]
