# Generated by Django 6.0.5 on 2026-05-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор/Викладач'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Статус публікації'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_transcript',
            field=models.BooleanField(default=False, verbose_name='Наявність текстового транскрипту'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_alerts_count',
            field=models.IntegerField(default=5, verbose_name='Загальна кількість сповіщень подій (A_tot)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript_text',
            field=models.TextField(blank=True, verbose_name='Текст конспекту лекції'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.IntegerField(default=15, help_text='Тривалість відео у хвилинах (V_tot)', verbose_name='Тривалість відео (хв)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visual_alerts_count',
            field=models.IntegerField(default=5, verbose_name='Кількість візуалізованих сповіщень (A_vis)'),
        ),
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(max_length=200, verbose_name='Назва лабораторної роботи')),
                ('file', models.FileField(upload_to='labs/', verbose_name='Файл виконаної роботи')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оцінка (за 12-бальною шкалою)')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Коментар викладача')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус перевірки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Лабораторна робота',
                'verbose_name_plural': 'Лабораторні роботи',
            },
        ),
    ]
