# Generated by Django 6.0.5 on 2026-05-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_author_course_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('description', models.TextField(verbose_name='Опис та інструкція')),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to='instructions/', verbose_name='Файл з методичкою')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Завдання до лабораторної',
                'verbose_name_plural': 'Завдання до лабораторних',
            },
        ),
    ]
