# Generated by Django 6.0.5 on 2026-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_labassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name="Ім'я користувача")),
                ('email', models.EmailField(max_length=254, verbose_name='Email для відповіді')),
                ('message', models.TextField(verbose_name='Текст звернення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата звернення')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Звернення в підтримку',
                'verbose_name_plural': 'Звернення в підтримку',
            },
        ),
    ]
